# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      - sudo dpkg -i cf-cli_amd64.deb
      - cf -v
      - cf api https://api.ng.bluemix.net
      - cf auth $BLUEMIX_USER $BLUEMIX_PASSWORD
      - cf target -o $BLUEMIX_ORG -s $BLUEMIX_SPACE
      - cf a
      - cf push